 #生产环境的配置
 spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: "jdbc:mysql://sh-cynosdbmysql-grp-bmlet1ys.sql.tencentcdb.com:26919/usercenter"
    username: root
    password: 1210comeon!!!
    #设置session超时时间为一天
  session:
    timeout: 86400

