 #生产环境的配置
 spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usercenter?serverTimezone=GMT
    username: root
    password: root
    #设置session超时时间为一天


